### ISSUE TITLE
Opinions on functions vs transforms?

### ISSUE THREAD

**Issue by cmdcolin** [TomFrost/Jexl#102]
Great work on this library. I was wondering about your perspective on functions vs transforms

The readme suggests:
"While Transforms are the preferred way to change one value into another value, Jexl also allows top-level expression functions to be defined"

And I see that functions are actually a recent addition, so this is pretty cool, but do you have any reasons why transforms would be preferred?

**Comment by TomFrost** [comment]
Hi Colin!

At the end of the day it all boils down to personal preference, as there's no functional advantage to one over the other. The readme suggests transforms for two main reasons:

- Jexl was written for its expressions to be understood and written by savvy non-programmers. If you're not already used to the `function(arg)` syntax employed by C-like languages, then the subject-verb left-to-right flow of `price|roundUp` can feel more natural than `roundUp(price)`. I pulled that syntax from the family of popular template languages based on Django's (Twig, Nunjucks, etc) where those expressions were also optimized for folks who aren't traditionally programmers.
- With the introduction of functions that overlap the functionality of transforms, I felt it was good form to provide a guideline for the community so that Jexl code could be shared without having to be concerned with a codebase's internal conventions. So the options there were 1. Recommend using functions and deprecate transforms because they no longer have a use, or 2. Recommend using transforms for their original purpose and reap the ease-of-use benefits of my first point above. So I decided on #2.

So there you have it! If the function syntax makes more sense to you and anyone you have that might be writing these expressions, by all means you should use that :). If the above reasons could be impactful for you, though, transforms still have a nice place within the language definition.

Enjoy!

**Comment by cmdcolin** [comment]
gotcha thanks so much :)

**Comment by TomFrost** [comment]
You're welcome! :)
